#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

link() {
  local file="$1"
  ln -sfv $CURRENT_DIR/$file $HOME
}

link .bash_profile
link .bashrc
link .s3cfg
link .tmux.conf
link .vim
link .wyrdrc

mkdir -p $HOME/.config
ln -sfv $CURRENT_DIR/git/ $HOME/.config
ln -sfv $CURRENT_DIR/mutt/ $HOME/.config
ln -sfv $CURRENT_DIR/ssh_config $HOME/.ssh/config
ln -sfv $CURRENT_DIR/ssh_authorized_keys/ $HOME/.ssh/authorized_keys
